/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sales;

import classes.ConfirmationDialog;
import java.awt.event.KeyEvent;
import java.sql.*;

/**
 *
 * @author Administrator
 */
public class Sales_ProductSearchData extends javax.swing.JPanel {

    /**
     * Creates new form Sales_ProductSearchData
     */
    public Sales_ProductSearch sales_productsearch;

    Connection connection = null;
    Statement statement;
    ResultSet result;

    String Barcode = "404", Product_No = "404";
    public boolean confirm = false;

    public Sales_ProductSearchData(Sales_ProductSearch sales_productsearch, String Barcode) {
        this.connection = sales_productsearch.connection;
        this.sales_productsearch = sales_productsearch;
        this.Barcode = Barcode;
        initComponents();
        but_add.addFocusListener(sales_productsearch.scroll);
        showdata();
    }

    private void showdata() {
        try {
            statement = connection.createStatement();
            System.out.println("select `product_no.`, concat(barcode,'-',short_description)as product, quantity  from product where barcode = '" + Barcode + "'");
            result = statement.executeQuery("select `product_no.`, concat(barcode,'-',short_description)as product, quantity  from product where barcode = '" + Barcode + "'");
            if (result.next()) {
                Product_No = result.getString(1);
                label_itemdesc.setText(result.getString(2));
                label_itemqty.setText(result.getString(3));

                statement.close();
                result.close();
                statement = connection.createStatement();
                System.out.println("select * from product_price where `product_no.` = (select `product_no.` from product where barcode = '" + Barcode + "') order by new_price_date desc limit 1; ");
                result = statement.executeQuery("select * from product_price where `product_no.` = (select `product_no.` from product where barcode = '" + Barcode + "') order by new_price_date desc limit 1; ");
                if (result.next()) {
                    label_itemprice.setText(result.getDouble(5) + "");
                }
                statement.close();
                result.close();

            }
            statement.close();
            result.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        label_itemdesc = new javax.swing.JLabel();
        label_itemprice = new javax.swing.JLabel();
        but_add = new javax.swing.JButton();
        label_itemqty = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem1.setText("Add Item");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setOpaque(false);

        label_itemdesc.setText("ITEM DESCRIPTION");
        label_itemdesc.setMaximumSize(new java.awt.Dimension(350, 16));
        label_itemdesc.setMinimumSize(new java.awt.Dimension(350, 16));
        label_itemdesc.setPreferredSize(new java.awt.Dimension(400, 16));

        label_itemprice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_itemprice.setText("NO PRICE");
        label_itemprice.setMaximumSize(new java.awt.Dimension(90, 16));
        label_itemprice.setMinimumSize(new java.awt.Dimension(90, 16));
        label_itemprice.setPreferredSize(new java.awt.Dimension(90, 16));

        but_add.setText("<html> <center> Add Item  <br> <b>[F2]</b> </center> </html>");
        but_add.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                but_addFocusGained(evt);
            }
        });
        but_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_addActionPerformed(evt);
            }
        });
        but_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                but_addKeyReleased(evt);
            }
        });

        label_itemqty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_itemqty.setText("QTY");
        label_itemqty.setMaximumSize(new java.awt.Dimension(90, 16));
        label_itemqty.setMinimumSize(new java.awt.Dimension(90, 16));
        label_itemqty.setPreferredSize(new java.awt.Dimension(90, 16));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_itemdesc, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_itemqty, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_itemprice, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(but_add, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(but_add, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(label_itemdesc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_itemprice, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_itemqty, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.getViewport().setBorder(null);

        jScrollPane1.setViewportView(jMenuBar1);
    }// </editor-fold>//GEN-END:initComponents

    private void but_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_addActionPerformed
        // TODO add your handling code here:
        jMenuItem1ActionPerformed(evt);
    }//GEN-LAST:event_but_addActionPerformed

    private void but_addKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_but_addKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_F2) {
            jMenuItem1ActionPerformed(null);
        }
    }//GEN-LAST:event_but_addKeyReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        confirm = false;
//        int x = JOptionPane.showConfirmDialog(this, "Do you really want to add the selected item?", "D-TECH CONFIRMATION", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        ConfirmationDialog confirmationdialog = new ConfirmationDialog(sales_productsearch.sales_mainframe, true, this);
        confirmationdialog.setTitle("D-TECH CONFIRMATION");
        confirmationdialog.setContent("D-TECH CONFIRMATION", "Do you really want to add the selected item?");
        confirmationdialog.setVisible(true);

        if (confirm) {
            if (but_add.isFocusTraversable()) {
                sales_productsearch.additem();
            }
        } else {
            sales_productsearch.cancelitem();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void but_addFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_but_addFocusGained
        // TODO add your handling code here:
        System.err.println("Barcode Selected : " + Barcode);
        sales_productsearch.setselecteditem(Barcode);
        but_add.requestFocusInWindow();
    }//GEN-LAST:event_but_addFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_add;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_itemdesc;
    private javax.swing.JLabel label_itemprice;
    private javax.swing.JLabel label_itemqty;
    // End of variables declaration//GEN-END:variables

}
