/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sales;

import java.sql.*;
import javax.swing.*;

import java.awt.Component;
import javax.swing.SwingUtilities;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author Administrator
 */
public class Sales_ProductSearch extends javax.swing.JDialog {

    /**
     * Creates new form Sales_ProductSearch
     */
    public SrcollListener scroll = new SrcollListener();

    public Sales_Mainframe sales_mainframe;

    Connection connection = null;
    Statement statement;
    ResultSet result;

    boolean bulk_quantity = false;
    String Barcode = "404";
    int qty = 1;
    boolean valitqty = true;
    public boolean confirm = false;

    public Sales_ProductSearch(java.awt.Frame parent, boolean modal, Sales_Mainframe sales_mainframe) {
        super(parent, modal);
        this.connection = sales_mainframe.connection;
        this.sales_mainframe = sales_mainframe;
        initComponents();

        panel_boxdata.add(label_note);
        panel_boxdata.setBorder(new EmptyBorder(10, 10, 10, 10));
        setLocationRelativeTo(parent);
    }

    public Sales_ProductSearch(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_note = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        field_search = new javax.swing.JTextField();
        but_search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panel_boxdata = new javax.swing.JPanel();
        but_close = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        label_itemdesc = new javax.swing.JLabel();
        label_itemprice = new javax.swing.JLabel();
        label_itemqty = new javax.swing.JLabel();
        label_itemprice1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menufile = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        Menuoption = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        Menuitemoptquantity = new javax.swing.JMenuItem();

        label_note.setBackground(new java.awt.Color(204, 51, 0));
        label_note.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_note.setForeground(new java.awt.Color(255, 255, 255));
        label_note.setText("<html> &nbsp; Please read the ff.:  <ul>\n <li><b>[Tab]</b> to focus next component.</li>\n <li><b>[Enter]</b> to execute search filter. \n<li><b>[NUM]</b> to get bulk item.</li> \n<li><b>[F2]</b> to add item.</li> \n<li><b>[ESC]</b> to cancel and close window.</li> \n</ul> </html>");
        label_note.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(690, 375));
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PRODUCT INQUIRY");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        field_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_searchActionPerformed(evt);
            }
        });

        but_search.setText("<html>  SEARCH  <b>[ENTER]</b> </html>");
        but_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_searchActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(null);
        jScrollPane1.setAutoscrolls(true);

        panel_boxdata.setOpaque(false);
        panel_boxdata.setLayout(new javax.swing.BoxLayout(panel_boxdata, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(panel_boxdata);

        but_close.setText("<html> \nCLOSE  <b>[ESC]</b>\n</html>");
        but_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_closeActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setOpaque(false);

        label_itemdesc.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        label_itemdesc.setText("ITEM DESCRIPTION");
        label_itemdesc.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        label_itemdesc.setMaximumSize(new java.awt.Dimension(350, 16));
        label_itemdesc.setMinimumSize(new java.awt.Dimension(350, 16));
        label_itemdesc.setPreferredSize(new java.awt.Dimension(400, 16));

        label_itemprice.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        label_itemprice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_itemprice.setText("PRICE");
        label_itemprice.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        label_itemprice.setMaximumSize(new java.awt.Dimension(90, 16));
        label_itemprice.setMinimumSize(new java.awt.Dimension(90, 16));
        label_itemprice.setPreferredSize(new java.awt.Dimension(90, 16));

        label_itemqty.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        label_itemqty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_itemqty.setText("QTY");
        label_itemqty.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        label_itemqty.setMaximumSize(new java.awt.Dimension(90, 16));
        label_itemqty.setMinimumSize(new java.awt.Dimension(90, 16));
        label_itemqty.setPreferredSize(new java.awt.Dimension(90, 16));

        label_itemprice1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        label_itemprice1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_itemprice1.setText("ACTION");
        label_itemprice1.setMaximumSize(new java.awt.Dimension(90, 16));
        label_itemprice1.setMinimumSize(new java.awt.Dimension(90, 16));
        label_itemprice1.setPreferredSize(new java.awt.Dimension(90, 16));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_itemdesc, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_itemqty, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_itemprice, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_itemprice1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(label_itemprice1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(label_itemprice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_itemdesc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_itemqty, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(field_search)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(but_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(but_close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_search, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_search, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_close, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.getViewport().setBorder(null);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setOpaque(false);

        jMenuBar1.setPreferredSize(new java.awt.Dimension(41, 0));

        menufile.setText("FILE");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem1.setText("Close");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menufile.add(jMenuItem1);

        jMenuBar1.add(menufile);

        Menuoption.setText("OPTION");

        jMenuItem2.setText("Add Item");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Menuoption.add(jMenuItem2);

        Menuitemoptquantity.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_END, 0));
        Menuitemoptquantity.setText("Bulk Quantity");
        Menuitemoptquantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuitemoptquantityActionPerformed(evt);
            }
        });
        Menuoption.add(Menuitemoptquantity);

        jMenuBar1.add(Menuoption);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void but_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_closeActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(this, "Do you really want to close product inquiry?", "D-TECH CONFIRMATION", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (x == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_but_closeActionPerformed

    private void field_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_searchActionPerformed
        // TODO add your handling code here:
        but_searchActionPerformed(evt);
    }//GEN-LAST:event_field_searchActionPerformed

    private void but_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_searchActionPerformed
        // TODO add your handling code here:
        if (field_search.getText().isEmpty()) {
            panel_boxdata.removeAll();
            panel_boxdata.add(label_note);
            panel_boxdata.updateUI();
            return;
        }
        searchdata(field_search.getText());
    }//GEN-LAST:event_but_searchActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        but_closeActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MenuitemoptquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuitemoptquantityActionPerformed
        // TODO add your handling code here:
        System.err.println("Activate " + Menuitemoptquantity.getText());
        if (Menuitemoptquantity.getText().equalsIgnoreCase("Bulk Quantity")) {
            bulk_quantity = true;
            Menuitemoptquantity.setText("Single Quantity");
        } else {
            qty = 1;
            bulk_quantity = false;
            Menuitemoptquantity.setText("Bulk Quantity");
        }
        jMenuItem2ActionPerformed(evt);
    }//GEN-LAST:event_MenuitemoptquantityActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        if (!bulk_quantity) {
            qty = 1;
            valitqty = true;
        } else {
            try {

                qty = (int) Integer.parseInt(JOptionPane.showInputDialog("Enter Quantity:"));
                valitqty = true;

            } catch (NumberFormatException e) {
                System.err.println(e.getMessage());
                JOptionPane.showConfirmDialog(this, "Enter a valid input for quantity.", "D-TECH WARNING", JOptionPane.PLAIN_MESSAGE, JOptionPane.WARNING_MESSAGE);
                valitqty = false;
                qty = 1;
            }
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    public void addselecteditem(String Barcode) {
        this.Barcode = Barcode;
        if (valitqty) {
            sales_mainframe.addselectitem(Barcode, qty);
            qty = 1;
            bulk_quantity = false;
            Menuitemoptquantity.setText("Bulk Quantity");
        }
    }

    public void setselecteditem(String Barcode) {
        this.Barcode = Barcode;
    }

    public void additem() {
        sales_mainframe.addselectitem(Barcode, qty);
        qty = 1;
        bulk_quantity = false;
        Menuitemoptquantity.setText("Bulk Quantity");

    }
    public void cancelitem() {
        qty = 1;
        bulk_quantity = false;
        Menuitemoptquantity.setText("Bulk Quantity");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sales_ProductSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sales_ProductSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sales_ProductSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sales_ProductSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Sales_ProductSearch dialog = new Sales_ProductSearch(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Menuitemoptquantity;
    private javax.swing.JMenu Menuoption;
    private javax.swing.JButton but_close;
    private javax.swing.JButton but_search;
    private javax.swing.JTextField field_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_itemdesc;
    private javax.swing.JLabel label_itemprice;
    private javax.swing.JLabel label_itemprice1;
    private javax.swing.JLabel label_itemqty;
    private javax.swing.JLabel label_note;
    private javax.swing.JMenu menufile;
    private javax.swing.JPanel panel_boxdata;
    // End of variables declaration//GEN-END:variables
    public class SrcollListener implements FocusListener {

        @Override
        public void focusGained(FocusEvent e) {
            final Component component = e.getComponent();
            if (component != null && component.getParent() != null && component.getParent() instanceof JComponent) {
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        ((JComponent) component.getParent()).scrollRectToVisible(component.getBounds());
                    }
                });
            }
        }

        @Override
        public void focusLost(FocusEvent e) {
        }
    }

    private void searchdata(String data) {
        try {
            panel_boxdata.removeAll();
            statement = connection.createStatement();
//            Product_No., Barcode, Short_Description, Description, Type, Category, Quantity, Buyby, isActive, isBookable, Company_No., Datetime_Created, Datetime_Updated, cancelflag, User_ID
            System.out.println("select * from product where barcode like '%" + data + "%' OR short_description like '%" + data + "%'");
            result = statement.executeQuery("select * from product where barcode like '%" + data + "%' OR short_description like '%" + data + "%'");
            while (result.next()) {
                Sales_ProductSearchData psd = new Sales_ProductSearchData(this, result.getString(2));
                psd.addFocusListener(scroll);
                panel_boxdata.add(psd, result.getString(2));
//                panel_boxdata.add(new Sales_ProductSearchData(this, result.getString(2)));
            }
            panel_boxdata.updateUI();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, e.getMessage(), "D-TECH WARNING", JOptionPane.PLAIN_MESSAGE, JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
}
