/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory.form;

import inventory.Inventory_SystemConfig;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class Inventory_CompanyForm extends javax.swing.JDialog {

    /**
     * Creates new form Inventory_CompanyForm
     */
    Inventory_SystemConfig inventory_systemconfig;

    Connection connection = null;
    Statement statement;
    ResultSet result;

    String Company_No = "", validated_fields = "Please check the ff. fields:\n\n";

    DefaultTableModel company_dtm;

    public Inventory_CompanyForm() {
    }

    public Inventory_CompanyForm(java.awt.Frame parent, boolean modal, Inventory_SystemConfig inventory_systemconfig) {
        super(parent, modal);
        this.connection = inventory_systemconfig.connection;
        this.inventory_systemconfig = inventory_systemconfig;
        initComponents();
        setLocationRelativeTo(parent);
//        setlastID();

    }

    public Inventory_CompanyForm(java.awt.Frame parent, boolean modal, Inventory_SystemConfig inventory_systemconfig, String Company_No) {
        super(parent, modal);
        this.connection = inventory_systemconfig.connection;
        this.inventory_systemconfig = inventory_systemconfig;
        this.Company_No = Company_No;
        initComponents();
        setLocationRelativeTo(parent);

        but_save.setText("UPDATE");
        restoredata(Company_No);
    }
   public void viewcompanyonly(){
       field_compno.setEditable(false);
       field_compname.setEditable(false);
       field_compowner.setEditable(false);
       field_comptelno.setEditable(false);
       field_compemail.setEditable(false);
       field_compaddress.setEditable(false);
       field_compaddress1.setEditable(false);
       but_browse.setEnabled(false);
       combo_compisactive.setEnabled(false);
       radioisdefault.setEnabled(false);
       but_save.setVisible(false);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        but_close = new javax.swing.JButton();
        but_save = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        field_compno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        field_compname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        field_compowner = new javax.swing.JTextField();
        field_comptelno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        field_compemail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        field_compaddress = new javax.swing.JTextArea();
        but_browse = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        field_compaddress1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        combo_compisactive = new javax.swing.JComboBox<>();
        radioisdefault = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("COMPANY FORM");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 0));
        jLabel1.setText("COMPANY FORM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 0));

        but_close.setText("CLOSE");
        but_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_closeActionPerformed(evt);
            }
        });

        but_save.setText("SAVE");
        but_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(but_save, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(but_close, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but_close, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_save, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Company No.");

        field_compno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_compnoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Company Name");

        field_compname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_compnameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Company Owner");

        field_compowner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_compownerActionPerformed(evt);
            }
        });

        field_comptelno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_comptelnoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tel No.");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Email Address");

        field_compemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_compemailActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Street/Prk./Brgy.");

        field_compaddress.setColumns(20);
        field_compaddress.setRows(5);
        jScrollPane1.setViewportView(field_compaddress);

        but_browse.setText("Browse");
        but_browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_browseActionPerformed(evt);
            }
        });

        field_compaddress1.setColumns(20);
        field_compaddress1.setRows(5);
        jScrollPane2.setViewportView(field_compaddress1);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("City/Province");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Company Logo");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        combo_compisactive.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "YES", "NO" }));
        combo_compisactive.setBorder(null);
        combo_compisactive.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        radioisdefault.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radioisdefault.setText("Set as Default");
        radioisdefault.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_browse, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(radioisdefault, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                        .addComponent(combo_compisactive, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(field_compno)
                        .addGap(335, 335, 335))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(field_compname)
                            .addComponent(field_compowner)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1)
                                    .addComponent(field_comptelno, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2)
                                    .addComponent(field_compemail, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))))))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(field_compno, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(field_compname, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(field_compowner, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(field_comptelno, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(field_compemail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(4, 4, 4))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(but_browse, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(combo_compisactive, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioisdefault)
                                .addGap(2, 2, 2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void but_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_closeActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(this, "Do you really want to cancel adding/updating company?", "CONFIRMATION", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (x == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_but_closeActionPerformed

    private void field_compnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_compnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_compnoActionPerformed

    private void field_compnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_compnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_compnameActionPerformed

    private void field_compownerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_compownerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_compownerActionPerformed

    private void field_comptelnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_comptelnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_comptelnoActionPerformed

    private void field_compemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_compemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_compemailActionPerformed

    private void but_browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_browseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_but_browseActionPerformed

    private void but_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_saveActionPerformed
        // TODO add your handling code here:
        if (validate_field()) {
            JOptionPane.showConfirmDialog(this, validated_fields, "D-TECH WARNING", JOptionPane.PLAIN_MESSAGE, JOptionPane.WARNING_MESSAGE);
            return;
        }
        boolean active = true;
        if (combo_compisactive.getSelectedIndex() > 1) {
            active = false;
        }
        try {

            if (radioisdefault.isSelected()) {
                statement = connection.createStatement();
                statement.executeUpdate("update `company` set isdefault = 0;");
                statement.close();
            }
            if (but_save.getText().equalsIgnoreCase("save")) {

                statement = connection.createStatement();
//                Company_No., Company_Name, Owner, Contact_No., Email_Address, Address, Logo, isActive, Datetime_Created, Datetime_Updated, isDefault
                statement.executeUpdate("insert into company values('"
                        + field_compno.getText() + "','"
                        + field_compname.getText() + "','"
                        + field_compowner.getText() + "','"
                        + field_comptelno.getText() + "','"
                        + field_compemail.getText() + "','"
                        + field_compaddress.getText().trim() + "','"
                        + field_compaddress1.getText().trim() + "',null,"
                        + active + ",'"
                        + new SimpleDateFormat("yyyy-MM-d HH:mm:ss").format(new Date()) + "','"
                        + new SimpleDateFormat("yyyy-MM-d HH:mm:ss").format(new Date()) + "',0," + radioisdefault.isSelected() + ")");

                JOptionPane.showConfirmDialog(this, "Company Successfully Added!", "D-TECH INFORMATION", JOptionPane.PLAIN_MESSAGE, JOptionPane.INFORMATION_MESSAGE);

            } else {
                statement = connection.createStatement();
                statement.executeUpdate("update company set Company_Name ='"
                        + field_compname.getText() + "', Owner ='"
                        + field_compowner.getText() + "', `Contact_No.` ='"
                        + field_comptelno.getText() + "', Email_Address ='"
                        + field_compemail.getText() + "', Address1 ='"
                        + field_compaddress.getText().trim() + "', Address2 ='"
                        + field_compaddress.getText().trim() + "', isActive ="
                        + active + ",Datetime_Updated ='"
                        + new SimpleDateFormat("yyyy-MM-d HH:mm:ss").format(new Date()) + "', isdefault ="
                        + radioisdefault.isSelected() + " where `Company_No.` = '"
                        + Company_No + "'");

                JOptionPane.showConfirmDialog(this, "Company Successfully Updated!", "D-TECH INFORMATION", JOptionPane.PLAIN_MESSAGE, JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }

            statement.close();
            inventory_systemconfig.refreshtable();
            clearfield();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, e.getMessage(), "D-TECH WARNING", JOptionPane.PLAIN_MESSAGE, JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_but_saveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_browse;
    private javax.swing.JButton but_close;
    private javax.swing.JButton but_save;
    private javax.swing.JComboBox<String> combo_compisactive;
    private javax.swing.JTextArea field_compaddress;
    private javax.swing.JTextArea field_compaddress1;
    private javax.swing.JTextField field_compemail;
    private javax.swing.JTextField field_compname;
    private javax.swing.JTextField field_compno;
    private javax.swing.JTextField field_compowner;
    private javax.swing.JTextField field_comptelno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton radioisdefault;
    // End of variables declaration//GEN-END:variables

    private boolean validate_field() {
        boolean validate = false;
        validated_fields = "Please check the ff. fields:\n\n";
        if (field_compno.getText().isEmpty()) {
            validated_fields = validated_fields + "* Invalid Input for Company No..\n";
            validate = true;
            return validate;
        }
        if (field_compname.getText().isEmpty()) {
            validated_fields = validated_fields + "* Invalid Input for Company Name.\n";
            validate = true;
            return validate;
        }
        if (field_compowner.getText().isEmpty()) {
            validated_fields = validated_fields + "* Invalid Input for Company Owner.\n";
            validate = true;
            return validate;
        }
        if (field_comptelno.getText().isEmpty()) {
            validated_fields = validated_fields + "* Invalid Input for Company Tel No..\n";
            validate = true;
            return validate;
        }
        if (field_compemail.getText().isEmpty()) {
            validated_fields = validated_fields + "* Invalid Input for Company Email Address.\n";
            validate = true;
            return validate;
        }
        if (field_compaddress.getText().isEmpty()) {
            validated_fields = validated_fields + "* Invalid Input for Company Address 1.\n";
            validate = true;
            return validate;
        }
        if (field_compaddress.getText().isEmpty()) {
            validated_fields = validated_fields + "* Invalid Input for Company Address 2.\n";
            validate = true;
            return validate;
        }
        return validate;
    }

    private void clearfield() {
//        setlastID();
        field_compname.setText(null);
        field_compowner.setText(null);
        field_comptelno.setText(null);
        field_compemail.setText(null);
        field_compaddress.setText(null);
        field_compaddress.setText(null);
        combo_compisactive.setSelectedIndex(0);
    }

    private void restoredata(String company_no) {
        try {
            statement = connection.createStatement();
//            Company_No., Company_Name, Owner, Contact_No., Email_Address, Address1, Address2, Logo, isActive, Datetime_Created, Datetime_Updated, isDefault
            result = statement.executeQuery("select * from company where `Company_No.` = '" + company_no + "'");
            if (result.next()) {
                field_compno.setText(result.getString(1));
                field_compname.setText(result.getString(2));
                field_compowner.setText(result.getString(3));
                field_comptelno.setText(result.getString(4));
                field_compemail.setText(result.getString(5));
                field_compaddress.setText(result.getString(6));
                field_compaddress1.setText(result.getString(7));
                if (result.getBoolean(9)) {
                    combo_compisactive.setSelectedIndex(1);
                } else {
                    combo_compisactive.setSelectedIndex(2);
                }
                if (result.getBoolean(12)) {
                    radioisdefault.setSelected(true);
                } else {
                    radioisdefault.setSelected(false);
                }
            }
            statement.close();
            result.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

//    private void setlastID() {
//        try {
//            statement = connection.createStatement();
//            result = statement.executeQuery("SELECT `Company_No.` FROM company c order by `Company_No.` desc limit 1;");
//            if (result.next()) {
//                field_compno.setText(result.getString(1));
//            }
//            statement.close();
//            result.close();
//
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//    }
}
