/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory.form;

import inventory.Inventory_ProductList;
import java.sql.*;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class Inventory_ProductForm extends javax.swing.JDialog {

    /**
     * Creates new form Inventory_ProductForm
     */
    Inventory_ProductList inventory_productlist;
    String validated_fields = "Please check the ff. fields:\n\n";

    Connection connection = null;
    Statement statement;
    ResultSet result;

    String User_ID = "404", Product_No = "404";

    public Inventory_ProductForm(java.awt.Frame parent, boolean modal, Inventory_ProductList inventory_productlist) {
        super(parent, modal);
        initComponents();
        this.inventory_productlist = inventory_productlist;
        this.connection = inventory_productlist.connection;
        Product_No = getgeneratedproductNo();

        populateproductunit();
        populateproductcategory();
        setLocationRelativeTo(inventory_productlist);
    }

    public Inventory_ProductForm(java.awt.Frame parent, boolean modal, Inventory_ProductList inventory_productlist, String Product_No) {
        super(parent, modal);
        initComponents();
        this.inventory_productlist = inventory_productlist;
        this.connection = inventory_productlist.connection;
        this.Product_No = Product_No;

        but_save.setText("UPDATE");
        jRadioButton1.setVisible(false);
        field_productno.setText(Product_No);
        field_pbarcode.setText(Product_No);
        field_productno.setEnabled(false);
        field_pbarcode.setEnabled(false);
        field_pcost.setEnabled(false);
        field_pprice.setEnabled(false);

        restoredata();
        setLocationRelativeTo(inventory_productlist);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        combo_pstype = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        field_psaleamount = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        combo_pschedule = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        combo_psdatesale = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        combo_pedatesale = new javax.swing.JComboBox<>();
        but_ssaledeactivate = new javax.swing.JButton();
        but_ssaleactivate = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        but_save = new javax.swing.JButton();
        but_cancel = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel_pdetails = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        field_psdescription = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        field_productno = new javax.swing.JTextField();
        combo_pcategory = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        combo_ptype = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        field_pdescription = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        field_pbarcode = new javax.swing.JTextField();
        combo_pisactive = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        combo_psunit = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        combo_pbunit = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        combo_pnounit = new javax.swing.JSpinner();
        panel_pcost = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        field_pcost = new javax.swing.JFormattedTextField();
        field_pprice = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        label_pstock = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        combo_pbuybytype = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        radio_pisvatable = new javax.swing.JRadioButton();
        radio_pisbookable = new javax.swing.JRadioButton();

        jPanel4.setOpaque(false);

        combo_pstype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "Percentage", "Flatrate" }));
        combo_pstype.setBorder(null);
        combo_pstype.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Sale type");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Sale");

        field_psaleamount.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        field_psaleamount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        field_psaleamount.setText("0");
        field_psaleamount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                field_psaleamountFocusLost(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Schedule Sale");

        combo_pschedule.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "YES", "NO" }));
        combo_pschedule.setBorder(null);
        combo_pschedule.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Start Sale");

        combo_psdatesale.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT" }));
        combo_psdatesale.setBorder(null);
        combo_psdatesale.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("End Sale");

        combo_pedatesale.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT" }));
        combo_pedatesale.setBorder(null);
        combo_pedatesale.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        but_ssaledeactivate.setText("Diactivate");
        but_ssaledeactivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_ssaledeactivateActionPerformed(evt);
            }
        });

        but_ssaleactivate.setText("Activate");
        but_ssaleactivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_ssaleactivateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_pschedule, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_pstype, 0, 241, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(field_psaleamount))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_psdatesale, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_pedatesale, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(but_ssaleactivate, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(but_ssaledeactivate, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_pschedule, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_psdatesale, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_pedatesale, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_pstype, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_psaleamount, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but_ssaledeactivate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_ssaleactivate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(180, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PRODUCT FORM");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 0));
        jLabel1.setText("PRODUCT FORM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 0));

        but_save.setText("SAVE");
        but_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_saveActionPerformed(evt);
            }
        });

        but_cancel.setText("CANCEL");
        but_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(but_save, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(but_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(but_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_save, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panel_pdetails.setOpaque(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Category");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Type");

        field_psdescription.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("SKU");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Short Description");

        field_productno.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        field_productno.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        field_productno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                field_productnoFocusLost(evt);
            }
        });
        field_productno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                field_productnoKeyReleased(evt);
            }
        });

        combo_pcategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Food", "Non-food", "Service" }));
        combo_pcategory.setBorder(null);
        combo_pcategory.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Description");

        combo_ptype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Product", "Service" }));
        combo_ptype.setBorder(null);
        combo_ptype.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        field_pdescription.setColumns(20);
        field_pdescription.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        field_pdescription.setRows(5);
        field_pdescription.setBorder(null);
        jScrollPane1.setViewportView(field_pdescription);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Barcode");

        field_pbarcode.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        field_pbarcode.setForeground(new java.awt.Color(153, 153, 153));
        field_pbarcode.setText("n/a");
        field_pbarcode.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        field_pbarcode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                field_pbarcodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                field_pbarcodeFocusLost(evt);
            }
        });

        combo_pisactive.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "YES", "NO" }));
        combo_pisactive.setBorder(null);
        combo_pisactive.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Is Active");

        jRadioButton1.setText("Auto");
        jRadioButton1.setOpaque(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        combo_psunit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        combo_psunit.setBorder(null);
        combo_psunit.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Small Unit");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Big Unit");

        combo_pbunit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        combo_pbunit.setBorder(null);
        combo_pbunit.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("No. per unit");

        combo_pnounit.setModel(new javax.swing.SpinnerNumberModel());
        combo_pnounit.setValue(1);

        javax.swing.GroupLayout panel_pdetailsLayout = new javax.swing.GroupLayout(panel_pdetails);
        panel_pdetails.setLayout(panel_pdetailsLayout);
        panel_pdetailsLayout.setHorizontalGroup(
            panel_pdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pdetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_pdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_pdetailsLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(field_productno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton1)
                        .addGap(4, 4, 4))
                    .addGroup(panel_pdetailsLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_ptype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_pdetailsLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(field_psdescription, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
                    .addGroup(panel_pdetailsLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
                    .addGroup(panel_pdetailsLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(field_pbarcode)
                        .addContainerGap(2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_pdetailsLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_pcategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_pdetailsLayout.createSequentialGroup()
                        .addGroup(panel_pdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_pdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo_pbunit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combo_psunit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panel_pdetailsLayout.createSequentialGroup()
                        .addGroup(panel_pdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_pdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo_pisactive, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combo_pnounit)))))
        );
        panel_pdetailsLayout.setVerticalGroup(
            panel_pdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pdetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_pdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(field_productno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_pdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(field_pbarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_pdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(field_psdescription, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_pdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_pdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_pdetailsLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(combo_ptype, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_pdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_pcategory, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_pdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_pdetailsLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(combo_psunit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_pdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_pdetailsLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(combo_pbunit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_pdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(combo_pnounit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_pdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_pisactive, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DETAILS", panel_pdetails);

        panel_pcost.setOpaque(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Cost");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Sellling Price");

        field_pcost.setBackground(new java.awt.Color(0, 0, 0));
        field_pcost.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        field_pcost.setForeground(new java.awt.Color(153, 255, 0));
        field_pcost.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        field_pcost.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        field_pcost.setText("0.00");
        field_pcost.setDisabledTextColor(new java.awt.Color(153, 255, 0));
        field_pcost.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        field_pcost.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                field_pcostFocusLost(evt);
            }
        });

        field_pprice.setBackground(new java.awt.Color(0, 0, 0));
        field_pprice.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        field_pprice.setForeground(new java.awt.Color(153, 255, 0));
        field_pprice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        field_pprice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        field_pprice.setText("0.00");
        field_pprice.setDisabledTextColor(new java.awt.Color(153, 255, 0));
        field_pprice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        field_pprice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                field_ppriceFocusLost(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Remaining Stock");

        label_pstock.setBackground(new java.awt.Color(0, 0, 0));
        label_pstock.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_pstock.setForeground(new java.awt.Color(153, 255, 0));
        label_pstock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_pstock.setText("0");
        label_pstock.setOpaque(true);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Buy by type");

        combo_pbuybytype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PIECE", "HALF DOZEN", "DOZEN", "CUSTOM" }));
        combo_pbuybytype.setBorder(null);
        combo_pbuybytype.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        combo_pbuybytype.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                combo_pbuybytypePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("per piece");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("per piece");

        radio_pisvatable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radio_pisvatable.setText("Vat");
        radio_pisvatable.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        radio_pisvatable.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        radio_pisbookable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radio_pisbookable.setText("Bookable");
        radio_pisbookable.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        radio_pisbookable.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        javax.swing.GroupLayout panel_pcostLayout = new javax.swing.GroupLayout(panel_pcost);
        panel_pcost.setLayout(panel_pcostLayout);
        panel_pcostLayout.setHorizontalGroup(
            panel_pcostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_pcostLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_pcostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_pcostLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panel_pcostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(radio_pisbookable, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radio_pisvatable, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_pcostLayout.createSequentialGroup()
                        .addGroup(panel_pcostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_pcostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_pcostLayout.createSequentialGroup()
                                .addGroup(panel_pcostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(field_pcost, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(field_pprice)
                                    .addComponent(label_pstock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel_pcostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addComponent(combo_pbuybytype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panel_pcostLayout.setVerticalGroup(
            panel_pcostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pcostLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_pcostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_pcostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(field_pcost, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_pcostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(field_pprice, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_pcostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_pcostLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_pcostLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(label_pstock, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_pcostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_pbuybytype, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(219, 219, 219)
                .addComponent(radio_pisvatable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radio_pisbookable)
                .addContainerGap())
        );

        jTabbedPane1.addTab("OTHERS", panel_pcost);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void but_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_cancelActionPerformed
        // TODO add your handling code here:
        if (!but_save.isVisible()) {
            dispose();
            return;
        }

        int x = JOptionPane.showConfirmDialog(this, "Do you really want to cancel adding/updating item?", "CONFIRMATION", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (x == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_but_cancelActionPerformed

    private void but_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_saveActionPerformed
        // TODO add your handling code here:
        if (validate_field()) {
            JOptionPane.showMessageDialog(this, validated_fields);
            validated_fields = "Please check the ff. fields:\n\n";
            return;
        }
        boolean active = true, vatable = radio_pisvatable.isSelected(), bookable = radio_pisbookable.isSelected();
        int buyby = 0;
        if (combo_pisactive.getSelectedIndex() > 1) {
            active = false;
        }
        switch (combo_pbuybytype.getSelectedItem().toString()) {
            case "PIECE":
                buyby = 1;
                break;
            case "HALF DOZEN":
                buyby = 6;
                break;
            case "DOZEN":
                buyby = 12;
                break;
            default:
                try {
                    buyby = ((int) Integer.parseInt(combo_pbuybytype.getSelectedItem().toString()));
                } catch (NumberFormatException e) {
                    System.err.print(e.getMessage());
                    buyby = 1;
                }
                break;
        }

        String currentDatetime = new SimpleDateFormat("yyyy-MM-d hh:mm:ss").format(new Date());
        try {
//            Product_No., Barcode, Short_Description, Description, Type, Category, Quantity, Buybytype, isActive, isVatable, Company_No., Datetime_Created, Datetime_Updated, cancelflag
            if (but_save.getText().equalsIgnoreCase("save")) {
                statement = connection.createStatement();
                statement.executeUpdate("insert into product values('"
                        + field_productno.getText() + "','"
                        + field_pbarcode.getText() + "','"
                        + field_psdescription.getText() + "','"
                        + field_pdescription.getText().trim() + "','"
                        + combo_ptype.getSelectedItem() + "','"
                        + combo_pcategory.getSelectedItem() + "',"
                        + label_pstock.getText() + ","
                        + buyby + ","
                        + active + ","
                        + vatable + ",'"
                        + bookable + ",'"
                        + inventory_productlist.inventory_mainframe.Company_No + "','"
                        + new SimpleDateFormat("yyyy-MM-d HH:mm:ss").format(new Date()) + "','"
                        + new SimpleDateFormat("yyyy-MM-d HH:mm:ss").format(new Date()) + "', 0, '" + inventory_productlist.inventory_mainframe.userID + "','"
                        + combo_psunit.getSelectedItem() + "','"
                        + combo_pbunit.getSelectedItem() + "',"
                        + combo_pnounit.getValue() + ")");
                statement.close();

//                Cost_No., Product_No., Old_Cost, Old_Cost_Date, New_Cost, New_Cost_Date, User_ID, Datetime_Created, Datetime_Updated
                statement = connection.createStatement();
                statement.executeUpdate("insert into product_cost values('CST-"
                        + field_productno.getText() + "','"
                        + field_productno.getText() + "','"
                        + field_pcost.getText() + "','"
                        + new SimpleDateFormat("yyyy-MM-d HH:mm:ss").format(new Date()) + "','"
                        + field_pcost.getText() + "','"
                        + new SimpleDateFormat("yyyy-MM-d HH:mm:ss").format(new Date()) + "','"
                        + inventory_productlist.inventory_mainframe.userID + "','"
                        + new SimpleDateFormat("yyyy-MM-d HH:mm:ss").format(new Date()) + "','"
                        + new SimpleDateFormat("yyyy-MM-d HH:mm:ss").format(new Date()) + "')");
                statement.close();
//                Price_No., Product_No., Old_Price, Old_Price_Date, New_Price, New_Price_Date, User_ID, Datetime_Created, Datetime_Updated
                statement = connection.createStatement();
                statement.executeUpdate("insert into product_price values('PRC-"
                        + field_productno.getText() + "','"
                        + field_productno.getText() + "','"
                        + field_pprice.getText() + "','"
                        + new SimpleDateFormat("yyyy-MM-d HH:mm:ss").format(new Date()) + "','"
                        + field_pprice.getText() + "','"
                        + new SimpleDateFormat("yyyy-MM-d HH:mm:ss").format(new Date()) + "','"
                        + inventory_productlist.inventory_mainframe.userID + "','"
                        + new SimpleDateFormat("yyyy-MM-d HH:mm:ss").format(new Date()) + "','"
                        + new SimpleDateFormat("yyyy-MM-d HH:mm:ss").format(new Date()) + "')");
                statement.close();

                JOptionPane.showConfirmDialog(this, "Product Successfully Added!", "D-TECH INFORMATION", JOptionPane.PLAIN_MESSAGE, JOptionPane.INFORMATION_MESSAGE);

            } else {
                statement = connection.createStatement();
                statement.executeUpdate("update product set barcode = '"
                        + field_pbarcode.getText() + "', short_description = '"
                        + field_psdescription.getText() + "', description = '"
                        + field_pdescription.getText().trim() + "', `type` = '"
                        + combo_ptype.getSelectedItem() + "', `category`='"
                        + combo_pcategory.getSelectedItem() + "', isactive ="
                        + active + ",`isVatable` ="
                        + vatable + ",`isBookable` ="
                        + bookable + ",`buyby` ="
                        + buyby + ",`quantity` ="
                        + label_pstock.getText() + ", `Smallunit` = '"
                        + combo_psunit.getSelectedItem() + "', `Bigunit` ='"
                        + combo_pbunit.getSelectedItem() + "', `Noperunit` ="
                        + combo_pnounit.getValue() + ", Datetime_Updated ='"
                        + new SimpleDateFormat("yyyy-MM-d HH:mm:ss").format(new Date()) + "' where `Product_No.` = '" + Product_No + "'");

                JOptionPane.showConfirmDialog(this, "Product Successfully Updated!", "D-TECH INFORMATION", JOptionPane.PLAIN_MESSAGE, JOptionPane.INFORMATION_MESSAGE);

                statement.close();
                dispose();
            }

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, e.getMessage(), "D-TECH WARNING", JOptionPane.PLAIN_MESSAGE, JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
            dispose();
        }
        inventory_productlist.showQuery("SELECT * FROM productlist p;");
        clearfield();
    }//GEN-LAST:event_but_saveActionPerformed

    private void field_pbarcodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_field_pbarcodeFocusGained
        // TODO add your handling code here:
        if (field_pbarcode.getText().equals("n/a")) {
            field_pbarcode.setText(null);
            field_pbarcode.setForeground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_field_pbarcodeFocusGained

    private void field_pbarcodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_field_pbarcodeFocusLost
        // TODO add your handling code here:
        if (field_pbarcode.getText().isEmpty()) {
            field_pbarcode.setText("n/a");
            field_pbarcode.setForeground(new java.awt.Color(153, 153, 153));
        } else {
            field_pbarcode.setForeground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_field_pbarcodeFocusLost

    private void field_pcostFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_field_pcostFocusLost
        // TODO add your handling code here:
        if (field_pcost.getText().isEmpty()) {
            field_pcost.setText("0");
        }
    }//GEN-LAST:event_field_pcostFocusLost

    private void field_ppriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_field_ppriceFocusLost
        // TODO add your handling code here:
        if (field_pprice.getText().isEmpty()) {
            field_pprice.setText("0");
        }
    }//GEN-LAST:event_field_ppriceFocusLost

    private void field_psaleamountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_field_psaleamountFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_field_psaleamountFocusLost

    private void field_productnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field_productnoKeyReleased
        // TODO add your handling code here:
        if (field_productno.getText().isEmpty()) {
            field_pbarcode.setText("n/a");
        } else {
            field_pbarcode.setText(field_productno.getText());
        }
    }//GEN-LAST:event_field_productnoKeyReleased

    private void field_productnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_field_productnoFocusLost
        // TODO add your handling code here:
        if (field_productno.getText().isEmpty()) {
            field_pbarcode.setText("n/a");
        }
    }//GEN-LAST:event_field_productnoFocusLost

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton1.isSelected()) {
            field_productno.setText(getgeneratedproductNo());
            field_pbarcode.setText(field_productno.getText());
        } else {
            field_productno.setText("");
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void but_ssaledeactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_ssaledeactivateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_but_ssaledeactivateActionPerformed

    private void but_ssaleactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_ssaleactivateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_but_ssaleactivateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void combo_pbuybytypePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_combo_pbuybytypePopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (combo_pbuybytype.getSelectedIndex() > -1) {
            int index = combo_pbuybytype.getSelectedIndex();
            if (combo_pbuybytype.getSelectedIndex() == 3) {
                combo_pbuybytype.setEditable(true);
            } else {
                combo_pbuybytype.setEditable(false);
            }

            if (combo_pbuybytype.getSelectedItem().toString().equalsIgnoreCase("CUSTOM")) {
                combo_pbuybytype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"PIECE", "HALF DOZEN", "DOZEN", ""}));
            } else {
                combo_pbuybytype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"PIECE", "HALF DOZEN", "DOZEN", combo_pbuybytype.getItemAt(3)}));
            }
            combo_pbuybytype.setSelectedIndex(index);
        }
    }//GEN-LAST:event_combo_pbuybytypePopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventory_ProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventory_ProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventory_ProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventory_ProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Inventory_ProductForm dialog = new Inventory_ProductForm(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_cancel;
    private javax.swing.JButton but_save;
    private javax.swing.JButton but_ssaleactivate;
    private javax.swing.JButton but_ssaledeactivate;
    private javax.swing.JComboBox<String> combo_pbunit;
    private javax.swing.JComboBox<String> combo_pbuybytype;
    private javax.swing.JComboBox<String> combo_pcategory;
    private javax.swing.JComboBox<String> combo_pedatesale;
    private javax.swing.JComboBox<String> combo_pisactive;
    private javax.swing.JSpinner combo_pnounit;
    private javax.swing.JComboBox<String> combo_pschedule;
    private javax.swing.JComboBox<String> combo_psdatesale;
    private javax.swing.JComboBox<String> combo_pstype;
    private javax.swing.JComboBox<String> combo_psunit;
    private javax.swing.JComboBox<String> combo_ptype;
    private javax.swing.JTextField field_pbarcode;
    private javax.swing.JFormattedTextField field_pcost;
    private javax.swing.JTextArea field_pdescription;
    private javax.swing.JFormattedTextField field_pprice;
    private javax.swing.JTextField field_productno;
    private javax.swing.JFormattedTextField field_psaleamount;
    private javax.swing.JTextField field_psdescription;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel label_pstock;
    private javax.swing.JPanel panel_pcost;
    private javax.swing.JPanel panel_pdetails;
    private javax.swing.JRadioButton radio_pisbookable;
    private javax.swing.JRadioButton radio_pisvatable;
    // End of variables declaration//GEN-END:variables

    private boolean validate_field() {
        boolean validate = false;
        if (field_productno.getText().isEmpty()) {
            validated_fields = validated_fields + "* Please Enter Product No.\n";
            validate = true;
        }
//        if (field_barcode.getText().isEmpty()) {
//            validated_fields = validated_fields + "* Invalid or Existing Barcode No.\n";
//            validate = true;
//        }
        if (field_psdescription.getText().isEmpty()) {
            validated_fields = validated_fields + "* Invalid Input for Short description\n";
            validate = true;
        }
        if (field_pdescription.getText().isEmpty()) {
            validated_fields = validated_fields + "* Invalid Input for Description\n";
            validate = true;
        }
        if (combo_ptype.getSelectedIndex() == 0) {
            validated_fields = validated_fields + "* Please select Product Type\n";
            validate = true;
        }
        if (combo_pcategory.getSelectedIndex() == 0) {
            validated_fields = validated_fields + "* Please select Product Category\n";
            validate = true;
        }
        if (combo_pisactive.getSelectedIndex() == 0) {
            validated_fields = validated_fields + "* Select Status option.\n";
            validate = true;
            return validate;
        }
//        if (combo_pbuybytype.getSelectedIndex() == 0) {
//            validated_fields = validated_fields + "* Select Buy by type option.\n";
//            validate = true;
//            return validate;
//        }
//        if (combo_pisbookable.getSelectedIndex() == 0) {
//            validated_fields = validated_fields + "* Select Bookable option.\n";
//            validate = true;
//            return validate;
//        }
        try {
            statement = connection.createStatement();
            result = statement.executeQuery("select * from product where short_description = '" + field_psdescription.getText() + "' or description = '" + field_pdescription.getText() + "' group by `product_no.` having  `product_no.` not in('" + Product_No + "')");
            if (result.next()) {
                validated_fields = validated_fields + "* Either Short Description and Description already exist.\n";
                return validate;
            }
            statement.close();
            result.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

        return validate;
    }

    private void clearfield() {
        field_psdescription.setText(null);
        field_pdescription.setText(null);
        combo_ptype.setSelectedIndex(0);
        combo_pcategory.setSelectedIndex(0);
        field_pcost.setText(null);
        field_pprice.setText(null);
        combo_pisactive.setSelectedIndex(0);
        combo_pbuybytype.setSelectedIndex(0);
        radio_pisvatable.setSelected(false);

        jTabbedPane1.setSelectedIndex(0);
        jRadioButton1ActionPerformed(null);
    }

    private String getgeneratedproductNo() {
        try {
            statement = connection.createStatement();
            System.out.println("select concat('101',year(now()),month(now()),day(now()),'000',substr(`Product_No.`,15)+1) as nextProductNo, `Product_No.` from product where date(Datetime_Created) = '" + new SimpleDateFormat("yyyy-MM-d").format(new Date()) + "' order by (substr(`Product_No.`,15)+1) desc limit 1");
            result = statement.executeQuery("select concat('101',year(now()),month(now()),day(now()),'000',substr(`Product_No.`,15)+1) as nextProductNo, `Product_No.` from product where date(Datetime_Created) = '" + new SimpleDateFormat("yyyy-MM-d").format(new Date()) + "' order by (substr(`Product_No.`,15)+1) desc limit 1");
            if (result.next()) {
                Product_No = result.getString(1);

            } else {
                Product_No = inventory_productlist.inventory_mainframe.Company_No
                        + new SimpleDateFormat("yyyyMMdd").format(new Date()) + "0001";
            }
            statement.close();
            result.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
        return Product_No;
    }

    private void restoredata() {
        try {
            populateproductunit();
            populateproductcategory();
//            Product_No., Barcode, Short_Description, Description, Type, Category, Quantity, Buyby, isActive, isVatable, Company_No., Datetime_Created, Datetime_Updated, cancelflag, User_ID, Smallunit, Bigunit, Noperunit
            statement = connection.createStatement();
            result = statement.executeQuery("SELECT * FROM product p where `Product_No.` = '" + Product_No + "'");
            if (result.next()) {
                field_psdescription.setText(result.getString(3));
                field_pdescription.setText(result.getString(4));

                combo_ptype.setSelectedItem(result.getString(5));
                combo_pcategory.setSelectedItem(result.getString(6));
                label_pstock.setText(result.getDouble(7) + "");

                switch (result.getInt(8)) {
                    case 1:
                        combo_pbuybytype.setSelectedIndex(0);
                        break;
                    case 6:
                        combo_pbuybytype.setSelectedIndex(1);
                        break;
                    case 12:
                        combo_pbuybytype.setSelectedIndex(2);
                        break;
                    default:
                        combo_pbuybytype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"PIECE", "HALF DOZEN", "DOZEN", (result.getInt(8) + "")}));
                        combo_pbuybytype.setEditable(true);
                        combo_pbuybytype.setSelectedIndex(3);
                }
                if (result.getBoolean(9)) {
                    combo_pisactive.setSelectedIndex(1);
                } else {
                    combo_pisactive.setSelectedIndex(2);
                }

                radio_pisvatable.setSelected(result.getBoolean(10));
                radio_pisbookable.setSelected(result.getBoolean(11));

                combo_psunit.setSelectedItem(result.getString(17));
                combo_pbunit.setSelectedItem(result.getString(18));
                combo_pnounit.setValue(result.getDouble(19));
                
                ResultSet result1 = statement.executeQuery("SELECT New_Cost FROM product_cost p where `Product_No.` = '" + Product_No + "'");
                if(result1.next()){
                    field_pcost.setText(new DecimalFormat("##0.00").format(result1.getDouble(1)));
                }
                result1.close();
                ResultSet result2 = statement.executeQuery("SELECT New_Price FROM product_price p where `Product_No.` = '" + Product_No + "'");
                if(result2.next()){
                    field_pprice.setText(new DecimalFormat("##0.00").format(result2.getDouble(1)));
                }
                result2.close();
            }
            statement.close();
            result.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void populateproductunit() {
        combo_psunit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Select"}));
        combo_pbunit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Select"}));
        try {
            statement = connection.createStatement();
            result = statement.executeQuery("SELECT * FROM product_unit p where unittype = 'Small Unit' and isActive = 1;");
            while (result.next()) {
                combo_psunit.addItem(result.getString(3));
            }
            statement.close();
            result.close();
            statement = connection.createStatement();
            result = statement.executeQuery("SELECT * FROM product_unit p where unittype = 'Big Unit' and isActive = 1;");
            while (result.next()) {
                combo_pbunit.addItem(result.getString(3));
            }
            statement.close();
            result.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void populateproductcategory() {
        combo_pcategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Select"}));
        try {
            statement = connection.createStatement();
            result = statement.executeQuery("SELECT * FROM product_category p where isActive = 1;");
            while (result.next()) {
                combo_pcategory.addItem(result.getString(2));
            }
            statement.close();
            result.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void setEnableallComponent(boolean enable) {
        field_productno.setEnabled(enable);
        field_pbarcode.setEnabled(enable);
        field_psdescription.setEnabled(enable);
        field_pdescription.setEnabled(enable);
        combo_ptype.setEnabled(enable);
        combo_pcategory.setEnabled(enable);
        combo_pisactive.setEnabled(enable);
        field_pcost.setEnabled(enable);
        field_pprice.setEnabled(enable);
        combo_pbuybytype.setEnabled(enable);
        radio_pisvatable.setEnabled(enable);

        combo_pschedule.setEnabled(enable);
        combo_psdatesale.setEnabled(enable);
        combo_pedatesale.setEnabled(enable);
        combo_pstype.setEnabled(enable);
        field_psaleamount.setEnabled(enable);
        but_save.setVisible(enable);
    }

}
