/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory.form;

import inventory.Inventory_ProductList;
import inventory.Inventory_UserSettings;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class Inventory_UserPositionForm extends javax.swing.JDialog {

    /**
     * Creates new form Inventory_PositionForm
     */
    Inventory_UserSettings inventory_usersettings;
    Connection connection = null;
    Statement statement;
    ResultSet result;

    String Position_No = "";

    public Inventory_UserPositionForm() {
    }
    DefaultTableModel position_dtm;

    public Inventory_UserPositionForm(java.awt.Frame parent, boolean modal,
            Inventory_UserSettings inventory_usersettings, Connection connection) {
        super(parent, modal);
        this.inventory_usersettings = inventory_usersettings;
        this.connection = connection;
        initComponents();
        setLocationRelativeTo(parent);

        showQuery("select concat(`Position_No.`,'-', `Position`)as Position, isActive, Datetime_Created, Datetime_Updated from user_position p;");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        but_close = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        field_position = new javax.swing.JTextField();
        but_inactive = new javax.swing.JButton();
        but_cancel = new javax.swing.JButton();
        but_newsaveupdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("POSITION SETTINGS");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 0));
        jLabel1.setText("POSTION SETTINGS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 0));

        but_close.setText("CLOSE");
        but_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(but_close, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(but_close, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Position");

        field_position.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        field_position.setEnabled(false);

        but_inactive.setText("INACTIVE");
        but_inactive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_inactiveActionPerformed(evt);
            }
        });

        but_cancel.setText("CANCEL");
        but_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_cancelActionPerformed(evt);
            }
        });

        but_newsaveupdate.setText("NEW");
        but_newsaveupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_newsaveupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(field_position, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(but_newsaveupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(but_inactive, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(but_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(field_position, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(but_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(but_inactive, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(but_newsaveupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        but_inactive.setVisible(false);
        but_cancel.setVisible(false);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Position", "isActive", "Created", "Updated"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(250);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(250);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(250);
            jTable1.getColumnModel().getColumn(1).setMinWidth(60);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(60);
        }

        jLabel3.setBackground(new java.awt.Color(204, 51, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Note: Double click on the list to edit.");
        jLabel3.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void but_inactiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_inactiveActionPerformed
        // TODO add your handling code here:
        try {
            boolean active;
            if (but_inactive.getText().equalsIgnoreCase("INACTIVE")) {
                active = false;
            } else {
                active = true;
            }
            statement = connection.createStatement();
            System.out.println("update user_position set isActive = " + active + ", "
                    + "Datetime_Updated = '" + new SimpleDateFormat("yyyy-MM-d HH:mm:ss").format(new Date()) + "' where `Position_No.` = '" + Position_No + "';");
            statement.executeUpdate("update user_position set isActive = " + active + ", "
                    + "Datetime_Updated = '" + new SimpleDateFormat("yyyy-MM-d HH:mm:ss").format(new Date()) + "' where `Position_No.` = '" + Position_No + "';");

            field_position.setText(null);

            statement.close();
            JOptionPane.showConfirmDialog(this, "Position Successfully " + but_inactive.getText() + "TED", "INFORMATION", JOptionPane.PLAIN_MESSAGE, JOptionPane.INFORMATION_MESSAGE);

            showQuery("select concat(`Position_No.`,'-', `Position`)as Position, isActive, Datetime_Created, Datetime_Updated from user_position p;");

            Position_No = "";
            field_position.setText(null);
            field_position.setEnabled(false);
            but_newsaveupdate.setText("New");
            but_newsaveupdate.setVisible(true);
            but_inactive.setVisible(false);
            but_cancel.setVisible(false);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_but_inactiveActionPerformed

    private void but_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_closeActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(this, "Do you really want to cancel adding/updating position?", "CONFIRMATION", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (x == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_but_closeActionPerformed

    private void but_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_cancelActionPerformed
        // TODO add your handling code here:
        Position_No = "";
        field_position.setText(null);
        field_position.setEnabled(false);
        but_newsaveupdate.setText("New");
        but_newsaveupdate.setVisible(true);
        but_inactive.setVisible(false);
        but_cancel.setVisible(false);
    }//GEN-LAST:event_but_cancelActionPerformed

    private void but_newsaveupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_newsaveupdateActionPerformed
        // TODO add your handling code here:
        if (but_newsaveupdate.getText().equalsIgnoreCase("new")) {
            but_newsaveupdate.setText("SAVE");
            field_position.setText(null);
            field_position.setEnabled(true);
            but_cancel.setVisible(true);
        } else if (but_newsaveupdate.getText().equalsIgnoreCase("save")) {
            if (field_position.getText().isEmpty()) {
                JOptionPane.showConfirmDialog(this, "Either your Input is empty or Invalid\n\nPlease check you input(s)", "D-TECH WARNING", JOptionPane.PLAIN_MESSAGE, JOptionPane.WARNING_MESSAGE);
                return;
            }
            try {
                statement = connection.createStatement();
                System.out.println("select * from user_position where `position` = '" + field_position.getText() + "'");
                result = statement.executeQuery("select * from user_position where `position` = '" + field_position.getText() + "'");
                if (result.next()) {
                    JOptionPane.showConfirmDialog(this, "Position already exist!", "WARNING", JOptionPane.PLAIN_MESSAGE, JOptionPane.WARNING_MESSAGE);
                    return;
                } else {
                    System.out.println("insert into user_position(`Position`, isActive, Datetime_Created, Datetime_Updated, User_ID)values"
                            + "('" + field_position.getText()
                            + "',true,'"
                            + new SimpleDateFormat("yyyy-MM-d HH:mm:ss").format(new Date()) + "','"
                            + new SimpleDateFormat("yyyy-MM-d HH:mm:ss").format(new Date()) + "','" + inventory_usersettings.inventory_mainframe.userID + "')");
                    statement.executeUpdate("insert into user_position(`Position`, isActive, Datetime_Created, Datetime_Updated, User_ID)values"
                            + "('" + field_position.getText()
                            + "',true,'"
                            + new SimpleDateFormat("yyyy-MM-d HH:mm:ss").format(new Date()) + "','"
                            + new SimpleDateFormat("yyyy-MM-d HH:mm:ss").format(new Date()) + "','" + inventory_usersettings.inventory_mainframe.userID + "')");

                    JOptionPane.showConfirmDialog(this, "Position Successfully Added!", "INFORMATION", JOptionPane.PLAIN_MESSAGE, JOptionPane.INFORMATION_MESSAGE);
                    field_position.setText(null);

                    showQuery("select concat(`Position_No.`,'-', `Position`)as Position, isActive, Datetime_Created, Datetime_Updated from user_position p;");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

        } else if (but_newsaveupdate.getText().equalsIgnoreCase("update")) {
            try {
                boolean active;
                if (but_inactive.getText().equalsIgnoreCase("INACTIVE")) {
                    active = false;
                } else {
                    active = true;
                }
                statement = connection.createStatement();
                System.out.println("update user_position set position = '" + field_position.getText() + "', "
                        + "Datetime_Updated = '" + new SimpleDateFormat("yyyy-MM-d HH:mm:ss").format(new Date()) + "', User_ID = '" + inventory_usersettings.inventory_mainframe.userID + "' where `Position_No.` = '" + Position_No + "';");
                statement.executeUpdate("update user_position set position = '" + field_position.getText() + "', "
                        + "Datetime_Updated = '" + new SimpleDateFormat("yyyy-MM-d HH:mm:ss").format(new Date()) + "', User_ID = '" + inventory_usersettings.inventory_mainframe.userID + "' where `Position_No.` = '" + Position_No + "';");
                field_position.setText(null);

                statement.close();

                JOptionPane.showConfirmDialog(this, "Position Successfully Updated!", "INFORMATION", JOptionPane.PLAIN_MESSAGE, JOptionPane.INFORMATION_MESSAGE);

                showQuery("select concat(`Position_No.`,'-', `Position`)as Position, isActive, Datetime_Created, Datetime_Updated from user_position p;");

                Position_No = "";
                field_position.setText(null);
                field_position.setEnabled(false);
                but_newsaveupdate.setText("New");
                but_newsaveupdate.setVisible(true);
                but_inactive.setVisible(false);
                but_cancel.setVisible(false);

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_but_newsaveupdateActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() >= 2) {
            if (jTable1.getSelectedRow() > -1) {
                but_newsaveupdate.setText("UPDATE");
                but_cancel.setVisible(true);
                but_inactive.setVisible(true);
                restoredata(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_cancel;
    private javax.swing.JButton but_close;
    private javax.swing.JButton but_inactive;
    private javax.swing.JButton but_newsaveupdate;
    private javax.swing.JTextField field_position;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void resettable() {
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Position", "isActive", "Created", "Updated"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(250);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(250);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(250);
            jTable1.getColumnModel().getColumn(1).setMinWidth(60);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(60);
        }

        position_dtm = (DefaultTableModel) jTable1.getModel();
    }

    public void showQuery(String query) {
        resettable();

        try {
            statement = connection.createStatement();
            result = statement.executeQuery(query);
            while (result.next()) {
//              `Position_No.`, `Position`, isActive, DatetimeCreated, DatetimeUpdated
                position_dtm.addRow(new Object[]{result.getString(1),
                    result.getBoolean(2),
                    result.getString(3),
                    result.getString(4)});
            }
            statement.close();
            result.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void restoredata(String position) {
        try {
            statement = connection.createStatement();
            System.out.println("select `Position_No.`, `Position`, isActive, Datetime_Created, Datetime_Updated from user_position where "
                    + "concat(`Position_No.`,'-', `Position`) = '" + position + "'");
            result = statement.executeQuery("select `Position_No.`, `Position`, isActive, Datetime_Created, Datetime_Updated from user_position where "
                    + "concat(`Position_No.`,'-', `Position`) = '" + position + "'");
            if (result.next()) {
                Position_No = result.getString(1);
                field_position.setText(result.getString(2));
                field_position.setEnabled(true);
                if (result.getBoolean(3)) {
                    but_inactive.setText("INACTIVE");
                } else {
                    but_inactive.setText("ACTIVE");
                }

            }
            statement.close();
            result.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
