/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory;

/**
 *
 * @author Administrator
 */
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.*;

public class Inventory_Mainframe extends javax.swing.JFrame {

    /**
     * Creates new form Inventory_Mainframe
     */
    javax.swing.Timer datetimer;

    Inventory_Dashboard inv_dashboard;
    Inventory_ProductList inv_productlist;
    Inventory_SupplierList inv_supplier;
    Inventory_WarehouseList inv_warehouse;
    Inventory_UserSettings inv_settings;
    Inventory_Pettycash inv_pettycash;
    Inventory_SystemConfig inv_systemconfig;
    Inventory_Reports inv_reports;

    Connection connection = null;
    Statement statement;
    ResultSet result;

    public String userID = "1", position = "tech-administrator", userFullname = "D-Tech Solutions", Company_No = "101";

    public Inventory_Mainframe(Connection connection) {
        this.connection = connection;
        initComponents();
        initDatetime();
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/DTECH-LOGO.jpg")).getImage());
        setLocationRelativeTo(null);
    }

    private void initDatetime() {

        label_dateday.setText(new SimpleDateFormat("EEEE").format(new Date()).toUpperCase());

        datetimer = new javax.swing.Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                label_datetime.setText(new SimpleDateFormat("MMMM dd, yyyy hh:mm:ss a").format(new Date()));
            }
        });
        datetimer.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_pcf = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        but_exit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        label_dateday = new javax.swing.JLabel();
        label_datetime = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        label_userlog = new javax.swing.JLabel();
        but_lock = new javax.swing.JButton();
        but_logout = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel_dashboard = new javax.swing.JPanel();
        panel_product = new javax.swing.JPanel();
        panel_supplier = new javax.swing.JPanel();
        panel_warehouse = new javax.swing.JPanel();
        panel_usersettings = new javax.swing.JPanel();
        panel_config = new javax.swing.JPanel();
        panel_reports = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();

        panel_pcf.setOpaque(false);

        javax.swing.GroupLayout panel_pcfLayout = new javax.swing.GroupLayout(panel_pcf);
        panel_pcf.setLayout(panel_pcfLayout);
        panel_pcfLayout.setHorizontalGroup(
            panel_pcfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_pcfLayout.setVerticalGroup(
            panel_pcfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DTECH SOLUTIONS - SALES AND INVENTORY SYSTEM");

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 0));
        jLabel1.setText("SALES INVENTORY");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Powered by D-Tech Solutions");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        but_exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        but_exit.setText("X");
        but_exit.setToolTipText("Exit");
        but_exit.setBorderPainted(false);
        but_exit.setContentAreaFilled(false);
        but_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(577, 577, 577))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(but_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(but_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        label_dateday.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        label_dateday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_dateday.setText("TUESDAY");

        label_datetime.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        label_datetime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label_datetime.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel4.setText("USER LOGIN");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        label_userlog.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        label_userlog.setText("D-TECH ADMINISTRATOR");

        but_lock.setText("LOCK");
        but_lock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_lockActionPerformed(evt);
            }
        });

        but_logout.setText("LOGOUT");
        but_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_userlog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(but_lock, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(but_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(label_datetime, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_dateday, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_userlog, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(but_lock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(but_logout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_dateday, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                        .addComponent(label_datetime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        panel_dashboard.setOpaque(false);

        javax.swing.GroupLayout panel_dashboardLayout = new javax.swing.GroupLayout(panel_dashboard);
        panel_dashboard.setLayout(panel_dashboardLayout);
        panel_dashboardLayout.setHorizontalGroup(
            panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_dashboardLayout.setVerticalGroup(
            panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("DASHBOARD", panel_dashboard);

        panel_product.setOpaque(false);

        javax.swing.GroupLayout panel_productLayout = new javax.swing.GroupLayout(panel_product);
        panel_product.setLayout(panel_productLayout);
        panel_productLayout.setHorizontalGroup(
            panel_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_productLayout.setVerticalGroup(
            panel_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("PRODUCT", panel_product);

        panel_supplier.setOpaque(false);

        javax.swing.GroupLayout panel_supplierLayout = new javax.swing.GroupLayout(panel_supplier);
        panel_supplier.setLayout(panel_supplierLayout);
        panel_supplierLayout.setHorizontalGroup(
            panel_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_supplierLayout.setVerticalGroup(
            panel_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("SUPPLIER", panel_supplier);

        panel_warehouse.setOpaque(false);

        javax.swing.GroupLayout panel_warehouseLayout = new javax.swing.GroupLayout(panel_warehouse);
        panel_warehouse.setLayout(panel_warehouseLayout);
        panel_warehouseLayout.setHorizontalGroup(
            panel_warehouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_warehouseLayout.setVerticalGroup(
            panel_warehouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("WAREHOUSE", panel_warehouse);

        panel_usersettings.setOpaque(false);

        javax.swing.GroupLayout panel_usersettingsLayout = new javax.swing.GroupLayout(panel_usersettings);
        panel_usersettings.setLayout(panel_usersettingsLayout);
        panel_usersettingsLayout.setHorizontalGroup(
            panel_usersettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_usersettingsLayout.setVerticalGroup(
            panel_usersettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("USER SETTINGS", panel_usersettings);

        panel_config.setOpaque(false);

        javax.swing.GroupLayout panel_configLayout = new javax.swing.GroupLayout(panel_config);
        panel_config.setLayout(panel_configLayout);
        panel_configLayout.setHorizontalGroup(
            panel_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_configLayout.setVerticalGroup(
            panel_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("SYSTEM CONFIG", panel_config);

        panel_reports.setOpaque(false);

        javax.swing.GroupLayout panel_reportsLayout = new javax.swing.GroupLayout(panel_reports);
        panel_reports.setLayout(panel_reportsLayout);
        panel_reportsLayout.setHorizontalGroup(
            panel_reportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_reportsLayout.setVerticalGroup(
            panel_reportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("REPORTS", panel_reports);

        jScrollPane1.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void but_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_exitActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(this, "Do you really want to exit?", "EXIT", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (x == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_but_exitActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:

        switch (jTabbedPane1.getSelectedIndex()) {
            case 0:
                inv_dashboard = new Inventory_Dashboard(this);
                jScrollPane1.setViewportView(inv_dashboard);
                break;
            case 1:
                inv_productlist = new Inventory_ProductList(this);
                inv_productlist.showQuery("SELECT * FROM productlist p;");
                jScrollPane1.setViewportView(inv_productlist);
                break;
            case 2:
                inv_supplier = new Inventory_SupplierList(this);
                inv_supplier.showQuery("SELECT * FROM supplierlist s;");
                jScrollPane1.setViewportView(inv_supplier);
                break;
            case 3:
                inv_warehouse = new Inventory_WarehouseList(this);
                inv_warehouse.showQuery("SELECT * FROM warehouselist w");
                jScrollPane1.setViewportView(inv_warehouse);
                break;
//            case 4:
//                inv_pettycash = new Inventory_Pettycash(this);
//                jScrollPane1.setViewportView(inv_pettycash);
//                break;
            case 4:
                inv_settings = new Inventory_UserSettings(this);
                inv_settings.showQuery("SELECT * FROM userlist ul where user_ID not in (select user_ID from engineer);");
                jScrollPane1.setViewportView(inv_settings);
                break;
            case 5:
                inv_systemconfig = new Inventory_SystemConfig(this);
                jScrollPane1.setViewportView(inv_systemconfig);
                break;
            case 6:
                inv_reports = new Inventory_Reports(this);
                jScrollPane1.setViewportView(inv_reports);
                break;
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void but_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_logoutActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(this, "Do you really want to logout?", "EXIT", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (x == JOptionPane.YES_OPTION) {
            datetimer.stop();
            inventory.Inventory_Login inventorylogin = new inventory.Inventory_Login();
            inventorylogin.setConnection(connection);
            inventorylogin.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_but_logoutActionPerformed

    private void but_lockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_lockActionPerformed
        // TODO add your handling code here:

        int x = JOptionPane.showConfirmDialog(this, "Do you really want to lock the system?", "EXIT", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (x == JOptionPane.YES_OPTION) {
            setVisible(false);
            inventory.Inventory_Login inventorylogin = new inventory.Inventory_Login(this);
            inventorylogin.setConnection(connection);
            inventorylogin.setVisible(true);
        }
    }//GEN-LAST:event_but_lockActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_exit;
    private javax.swing.JButton but_lock;
    public static javax.swing.JButton but_logout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel label_dateday;
    private javax.swing.JLabel label_datetime;
    private javax.swing.JLabel label_userlog;
    private javax.swing.JPanel panel_config;
    private javax.swing.JPanel panel_dashboard;
    private javax.swing.JPanel panel_pcf;
    private javax.swing.JPanel panel_product;
    private javax.swing.JPanel panel_reports;
    private javax.swing.JPanel panel_supplier;
    private javax.swing.JPanel panel_usersettings;
    private javax.swing.JPanel panel_warehouse;
    // End of variables declaration//GEN-END:variables

    void setuserID(String userID) {
        this.userID = userID;
        getuserFullname();
    }

    public void getuserFullname() {
        try {
            statement = connection.createStatement();
            result = statement.executeQuery("SELECT concat(lastname,', ',Firstname,' ',substr(Middlename,1,1))as userFullname FROM `user` u join `user_profile` up on u.`Profile_No.` = up.`Profile_No.` "
                    + "where u.User_ID = '" + userID + "'");

            if (result.next()) {
                userFullname = result.getString(1);
                label_userlog.setText(userFullname);
            }

            statement.close();
            result.close();

            getPosition();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void getPosition() {
        try {
            statement = connection.createStatement();
            System.out.println("SELECT p.`position` FROM `user` u join `user_profile` up on u.`Profile_No.` = up.`Profile_No.` join user_position p on up.`position_no.`= p.`position_no.` "
                    + "where u.User_ID = '" + userID + "'");
            result = statement.executeQuery("SELECT p.`position` FROM `user` u join `user_profile` up on u.`Profile_No.` = up.`Profile_No.` join user_position p on up.`position_no.`= p.`position_no.` "
                    + "where u.User_ID = '" + userID + "'");

            if (result.next()) {
                position = result.getString(1);
            }

            statement.close();
            result.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
